[project]
    site_name = "Sovereign's Regulations & Orders"
    site_description = ""
    site_author = "Judge Advocate General's Office"
    site_url = "https://.github.io/legal-codex/"
    copyright = """
    Copyright &copy; 2026 Site-78
    """
    extra_css = ["stylesheets/extra.css"]
    [project.theme]
    language = "en"
        features = [
            "announce.dismiss",
            "content.code.annotate",
            "content.code.copy",
            "content.code.select",
            "content.footnote.tooltips",
            "content.tabs.link",
            "content.tooltips",
            "navigation.footer",
            "navigation.indexes",
            "navigation.instant",
            "navigation.instant.prefetch",
            "navigation.path",
            "navigation.sections",
            "navigation.top",
            "navigation.tracking",
            "search.highlight",
            ]
        [[project.theme.palette]]
            scheme = "slate"
            primary = "JAG"
            accent = "JAG"